Models/Lanche.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjMaster.Models
{
    public class Lanche
    {
        public int Id { get; set; }
        public string Nome { get; set; }

        public string Genero { get; set; }
        [Range(1, 1000)]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Preco { get; set; }

        [StringLength(200)]
        public string ImagemUrl { get; set; }
    }
}

Controllers/CarrinhoCompraController.cs
using System.Linq;
using ProjMaster.Models;
using ProjMaster.Repositories;
using ProjMaster.ViewModels;
using Microsoft.AspNetCore.Mvc;
using ProjMaster.Controllers;

namespace MvcMovie.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(ILancheRepository lancheRepository, CarrinhoCompra carrinhoCompra )
        {
            _lancheRepository = lancheRepository;
            _carrinhoCompra = carrinhoCompra;
        }
        public IActionResult Index()
        {
            Autenticacao.CheckLogin(this);
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItens = itens;

            var carrinhoCompraViewModel = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
            };

            return View(carrinhoCompraViewModel);
        }
        public RedirectToActionResult AdicionarItemNoCarrinhoCompra( int lancheId)
        {
            Autenticacao.CheckLogin(this);
            var lancheSelecionado = _lancheRepository.lanches.FirstOrDefault(p => p.Id == lancheId );

            if (lancheSelecionado != null)
            {
                _carrinhoCompra.AdicionarAoCarrinho(lancheSelecionado);
            }
            return RedirectToAction("Index");
        }
        public IActionResult RemoverItemNoCarrinhoCompra( int lancheId)
        {
            Autenticacao.CheckLogin(this);
            var lancheSelecionado = _lancheRepository.lanches.FirstOrDefault(p => p.Id == lancheId );

            if (lancheSelecionado != null)
            {
                _carrinhoCompra.RemoverDoCarrinho(lancheSelecionado, 1);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/LancheController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjMaster.Data;
using ProjMaster.Models;

namespace ProjMaster.Controllers
{
    public class LancheController : Controller
    {
        private readonly ProjMasterContext _context;

        public LancheController(ProjMasterContext context)
        {
            _context = context;
        }

        // GET: Movies
        public async Task<IActionResult> IndexMain(string LancheGenero, string searchString)
        {  
            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from m in _context.Lanche orderby m.Genero select m.Genero;

            var movies = from m in _context.Lanche select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.Nome.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(LancheGenero))
            {
                movies = movies.Where(x => x.Genero == LancheGenero);
            }

            var lancheGeneroVM = new LancheGeneroViewModel
            {
                Generos = new SelectList(await genreQuery.Distinct().ToListAsync()),
                Lanches = await movies.ToListAsync()
            };

            return View(lancheGeneroVM);
        }
        
        [HttpPost]
        public string IndexMain(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }
        // GET: Movies
        public async Task<IActionResult> Index()
        {
            Autenticacao.CheckLogin(this);
            return View(await _context.Lanche.ToListAsync());
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Lanche
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            Autenticacao.CheckLogin(this);
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Genero,Preco,ImagemUrl,ImagemThumbnailUrl")] Lanche lanche)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lanche);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(lanche);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            Autenticacao.CheckLogin(this);
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Lanche.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Genero,Preco,ImagemUrl,ImagemThumbnailUrl")] Lanche lanche)
        {
            if (id != lanche.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lanche);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(lanche.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(lanche);
        }

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            Autenticacao.CheckLogin(this);
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Lanche
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Lanche.FindAsync(id);
            _context.Lanche.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            return _context.Lanche.Any(e => e.Id == id);
        }
    }
}

Views/Lanche/Create.cshtml
@model ProjMaster.Models.Lanche

@{
    ViewData["Title"] = "Create";
}
<div class="container mt-4">
<h1 class="text-center">Create</h1>

<h4 class="text-center">Lanche</h4>
<hr />
<div class="row justify-content-md-center">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagemUrl" class="control-label"></label>
                <input asp-for="ImagemUrl" class="form-control" />
                <span asp-validation-for="ImagemUrl" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <a asp-action="Index">Back to List</a>  | 
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</div>

Views/Lanche/Delete.cshtml
@model ProjMaster.Models.Lanche

@{
    ViewData["Title"] = "Delete";
}
<div class="container mt-4">
<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Lanche</h4>
    <hr />
    <dl class="row justify-content-md-center">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</div>

Views/Lanche/Details.cshtml
@model ProjMaster.Models.Lanche

@{
    ViewData["Title"] = "Details";
}
<div class="container mt-4">
<h1>Details</h1>

<div>
    <h4>Lanche</h4>
    <hr />
    <div class="Text-center view overlay hm-while-slight">
                <img src="@Model.ImagemUrl" class="img-fluid" alt="">
                <a href="#">
                    <div class="mask waves-effect waves-light"></div>
                </a>
            </div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="IndexMain">Back to List</a>
    <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-LancheId="@Model.Id">Incluir no Carrinho</a>
</div>
</div>

Views/Lanche/Edit.cshtml
@model ProjMaster.Models.Lanche

@{
    ViewData["Title"] = "Edit";
}
<div class="container mt-4">
<h1 class="text-center">Edit</h1>

<h4 class="text-center">Lanche</h4>
<hr />
<div class="row justify-content-md-center">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagemUrl" class="control-label"></label>
                <input asp-for="ImagemUrl" class="form-control" />
                <span asp-validation-for="ImagemUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a asp-action="Index">Back to List</a>  | 
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</div>

Views/Lanche/Index.cshtml
@model IEnumerable<ProjMaster.Models.Lanche>

@{
    ViewData["Title"] = "Index";
}
<div class="container mt-4">
<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagemUrl)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImagemUrl)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>

Views/Lanche/IndexMain.cshtml
@model ProjMaster.Models.LancheGeneroViewModel

@{
    ViewData["Title"] = "IndexMain";
}

<section>
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-block w-100" src="~/imagem/pizzas.jpg" alt="First slide">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>As Melhores Pizzas</h5>
                            <p>Veriedades de sabores, e promoções diarias. CONFIRA!</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="~/imagem/lanches.jpg" alt="Second slide">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>Os Melhoes Lanches</h5>
                            <p>Monte do seu jeito!</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="~/imagem/bebi.jpg" alt="Third slide">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>As Melhores Bebidas</h5>
                            <p>Para um melhor acompanhamento em todas as ocasiões</p>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </section>

<div>
    <nav class="navbar navbar-light justify-content-between border-2 border-dark border-top">
        <div class="container">
        <a class="navbar-brand">Pizzas</a>
        <form class="form-inline" asp-controller="Lanche" asp-action="IndexMain" method="get">
            <select class="custom-select" asp-for="LancheGenero" asp-items="Model.Generos">
                <option selected value="">Todos</option>
            </select>
            <input class="form-control mr-sm-2" type="search" placeholder="Pesquisa" aria-label="Search" asp-for="SearchString">
            <button class="btn btn-outline-light" type="submit"><ion-icon size="small" name="search-outline"></ion-icon></button>
        </form>
        </div>
    </nav>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="row">
                @foreach (var item in Model.Lanches) {
                    <div class="col-md-3 col-sm-3 col-lg-3">
                        <div class="card border border-dark" style="width: 16rem; margin: 8px auto; position: relative;">
                            <img src="@item.ImagemUrl" class="img-rounded" alt="" style="height: 10rem;"/>
                            <div class="card-body">
                                <h5 class="card-title">@Html.DisplayFor(modelItem => item.Nome)</h5>
                                <p class="card-text">@Html.DisplayFor(modelItem => item.Genero)</p>
                                <p>
                                    @Html.DisplayFor(modelItem => item.Preco)  |
                                    <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                                </p>
                                <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-LancheId="@item.Id">Incluir no Carrinho</a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>